### ISSUE TITLE
do "jailkit-lib.pl" failed, '.' is no longer in @INC;

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [virtualmin/webmin-jailkit#4]
Hi,

thanks for making this module. I think found a bug (Ubuntu Server 18.04). The module stays marked as "Unused", even though jailkit (and the module) are working correctly. I tried to manually run `install_check.pl` and it fails with the following message:

`do "jailkit-lib.pl" failed, '.' is no longer in @INC; did you mean do "./jailkit-lib.pl"? at ./install_check.pl line 3.`

So I did exactly what the error message told me to and changed line 3 to `do "./jailkit-lib.pl"`, reran the unused module check and it's now correctly showing up under "System"

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next release of that module
